services:
  - type: web
    name: my-web-service
    env: python
    buildCommand: ""
    startCommand: "gunicorn app:app"

  - type: worker
    name: my-celery-worker
    env: python
    buildCommand: ""
    startCommand: "celery -A app.celery worker --loglevel=info"
