services:
  - type: web
    name: my-mining-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: REDIS_URL
        value: "redis://<your-redis-url>"
